packages:
  - packages/*
  - build_defs/*
  - extension

overrides:
  "minimist@<1.2.6": "^1.2.8"
  "semver@<7.6.3": "^7.7.4"

allowBuilds: {}

patchedDependencies:
  "watcher@2.3.1": "patches/watcher@2.3.1.patch"

packageExtensions:
  "@secretlint/resolver":
    dependencies:
      "@secretlint/secretlint-rule-basicauth": "^10.2.2"
      "@secretlint/secretlint-rule-no-dotenv": "^10.2.2"
      "@secretlint/secretlint-rule-npm": "^10.2.2"
      "@secretlint/secretlint-rule-preset-recommend": "^10.2.2"
      "@secretlint/secretlint-rule-privatekey": "^10.2.2"
  "@textlint/resolver":
    dependencies:
      "@secretlint/secretlint-formatter-sarif": "^10.2.2"
  # chalk added as workaround for https://github.com/aspect-build/rules_lint/issues/752
  "eslint":
    dependencies:
      "chalk": "^4.0.0"

catalog:
  '@formatjs/intl-durationformat': ^0.10.7
  '@js-temporal/polyfill': ^0.5.1
  '@types/node': ^24.12.2
  ava: ^8.0.0
  cleye: ^2.6.0
  get-stream: ^9.0.1

catalogs:
  vscode:
    '@types/node': ^22.18.6
