packages:
  - 'packages/*'
  - 'build_defs/*'
  - 'extension'
catalog:
  "@formatjs/intl-durationformat": ^0.7.4
  "@js-temporal/polyfill": ^0.5.1
  "@types/node": ^20.19.1
  ava: ^6.4.0
  cleye: ^1.3.4
  get-stream: ^9.0.1
catalogs:
  vscode:
    "@types/node": ^20.17.50
