packages:
  - packages/*
  - build_defs/*
  - extension

catalog:
  '@formatjs/intl-durationformat': ^0.10.4
  '@js-temporal/polyfill': ^0.5.1
  '@types/node': ^24.12.2
  ava: ^7.0.0
  cleye: ^2.6.0
  get-stream: ^9.0.1

catalogs:
  vscode:
    '@types/node': ^22.18.6
