packages:
  - packages/*
  - build_defs/*
  - extension

catalog:
  '@formatjs/intl-durationformat': ^0.9.2
  '@js-temporal/polyfill': ^0.5.1
  '@types/node': ^24.10.8
  ava: ^6.4.1
  cleye: ^2.2.1
  get-stream: ^9.0.1

catalogs:
  vscode:
    '@types/node': ^22.18.6
