packages:
  - packages/*
  - build_defs/*
  - extension

catalog:
  '@formatjs/intl-durationformat': ^0.10.1
  '@js-temporal/polyfill': ^0.5.1
  '@types/node': ^24.11.0
  ava: ^7.0.0
  cleye: ^2.2.1
  get-stream: ^9.0.1

catalogs:
  vscode:
    '@types/node': ^22.18.6

ignoredOptionalDependencies:
  # Uses 'os: ["alpine"]' which we don't use, but breaks rules_js.
  # See https://github.com/aspect-build/rules_js/issues/2745
  - '@vscode/vsce-sign-alpine-arm64'
  - '@vscode/vsce-sign-alpine-x64'
