packages:
  - packages/*
  - build_defs/*
  - extension

catalog:
  '@formatjs/intl-durationformat': ^0.7.5
  '@js-temporal/polyfill': ^0.5.1
  '@types/node': ^24.7.0
  ava: ^6.4.1
  cleye: ^1.3.4
  get-stream: ^9.0.1

catalogs:
  vscode:
    '@types/node': ^22.18.6
