load("@rules_rust_wasm_bindgen//:defs.bzl", "rust_wasm_bindgen_toolchain")

# Copy of default toolchain in `@rules_rust_wasm_bindgen` with our dependency versions.
rust_wasm_bindgen_toolchain(
    name = "toolchain_impl",
    wasm_bindgen_cli = "@crates//:wasm-bindgen-cli__wasm-bindgen",
)

toolchain(
    name = "toolchain",
    toolchain = ":toolchain_impl",
    toolchain_type = "@rules_rust_wasm_bindgen//:toolchain_type",
)
