// Version pins for the DotSlash stubs in `.devcontainer/dotslash`, which are
// regenerated by `.github/workflows/update_dotslash_stubs.mjs`.
//
// `{version}` expands to `version`, `{versionNoV}` to `version` without a
// leading `v`.

/**
 * @typedef {object} Artifact
 * @property {string} url
 * @property {string} path Path to the executable, relative to the artifact root.
 * @property {"tar.gz" | "tar.xz" | "zip"} [format] Omitted when the artifact is the executable.
 *
 * @typedef {object} Tool
 * @property {string} version
 * @property {Record<string, Artifact>} platforms Keyed by DotSlash platform.
 */

const buildtools = name => ({
    // renovate: datasource=github-releases depName=bazelbuild/buildtools
    version: "v8.5.1",
    platforms: {
        "linux-x86_64": {
            url: `https://github.com/bazelbuild/buildtools/releases/download/{version}/${name}-linux-amd64`,
            path: name,
        },
        "linux-aarch64": {
            url: `https://github.com/bazelbuild/buildtools/releases/download/{version}/${name}-linux-arm64`,
            path: name,
        },
    },
});

/** @type {Record<string, Tool>} */
export const tools = {
    bazel: {
        // renovate: datasource=github-releases depName=bazelbuild/bazelisk
        version: "v1.29.0",
        platforms: {
            "linux-x86_64": {
                url: "https://github.com/bazelbuild/bazelisk/releases/download/{version}/bazelisk-linux-amd64",
                path: "bazel",
            },
            "linux-aarch64": {
                url: "https://github.com/bazelbuild/bazelisk/releases/download/{version}/bazelisk-linux-arm64",
                path: "bazel",
            },
        },
    },
    buildifier: buildtools("buildifier"),
    buildozer: buildtools("buildozer"),
    dprint: {
        // renovate: datasource=github-releases depName=dprint/dprint
        version: "0.55.2",
        platforms: {
            "linux-x86_64": {
                url: "https://github.com/dprint/dprint/releases/download/{version}/dprint-x86_64-unknown-linux-gnu.zip",
                format: "zip",
                path: "dprint",
            },
            "linux-aarch64": {
                url: "https://github.com/dprint/dprint/releases/download/{version}/dprint-aarch64-unknown-linux-gnu.zip",
                format: "zip",
                path: "dprint",
            },
        },
    },
    gh: {
        // renovate: datasource=github-releases depName=cli/cli
        version: "v2.97.0",
        platforms: {
            "linux-x86_64": {
                url: "https://github.com/cli/cli/releases/download/{version}/gh_{versionNoV}_linux_amd64.tar.gz",
                format: "tar.gz",
                path: "gh_{versionNoV}_linux_amd64/bin/gh",
            },
            "linux-aarch64": {
                url: "https://github.com/cli/cli/releases/download/{version}/gh_{versionNoV}_linux_arm64.tar.gz",
                format: "tar.gz",
                path: "gh_{versionNoV}_linux_arm64/bin/gh",
            },
        },
    },
    jscpd: {
        // renovate: datasource=github-releases depName=kucherenko/jscpd
        version: "v5.0.16",
        platforms: {
            "linux-x86_64": {
                url: "https://github.com/kucherenko/jscpd/releases/download/{version}/jscpd-linux-x64-gnu.tar.gz",
                format: "tar.gz",
                path: "jscpd",
            },
            "linux-aarch64": {
                url: "https://github.com/kucherenko/jscpd/releases/download/{version}/jscpd-linux-arm64-gnu.tar.gz",
                format: "tar.gz",
                path: "jscpd",
            },
        },
    },
    node: {
        // renovate: datasource=github-tags depName=nodejs/node
        version: "v26.7.0",
        platforms: {
            "linux-x86_64": {
                url: "https://nodejs.org/dist/{version}/node-{version}-linux-x64.tar.xz",
                format: "tar.xz",
                path: "node-{version}-linux-x64/bin/node",
            },
            "linux-aarch64": {
                url: "https://nodejs.org/dist/{version}/node-{version}-linux-arm64.tar.xz",
                format: "tar.xz",
                path: "node-{version}-linux-arm64/bin/node",
            },
        },
    },
    pnpm: {
        // renovate: datasource=npm depName=pnpm
        version: "11.22.0",
        platforms: {
            "linux-x86_64": {
                url: "https://github.com/pnpm/pnpm/releases/download/v{version}/pnpm-linux-x64.tar.gz",
                format: "tar.gz",
                path: "pnpm",
            },
            "linux-aarch64": {
                url: "https://github.com/pnpm/pnpm/releases/download/v{version}/pnpm-linux-arm64.tar.gz",
                format: "tar.gz",
                path: "pnpm",
            },
        },
    },
    rustup: {
        // renovate: datasource=github-tags depName=rust-lang/rustup
        version: "1.29.0",
        platforms: {
            "linux-x86_64": {
                url: "https://static.rust-lang.org/rustup/archive/{version}/x86_64-unknown-linux-gnu/rustup-init",
                path: "rustup",
            },
            "linux-aarch64": {
                url: "https://static.rust-lang.org/rustup/archive/{version}/aarch64-unknown-linux-gnu/rustup-init",
                path: "rustup",
            },
        },
    },
    starpls: {
        // renovate: datasource=github-releases depName=withered-magic/starpls
        version: "v0.1.22",
        platforms: {
            "linux-x86_64": {
                url: "https://github.com/withered-magic/starpls/releases/download/{version}/starpls-linux-amd64",
                path: "starpls",
            },
            "linux-aarch64": {
                url: "https://github.com/withered-magic/starpls/releases/download/{version}/starpls-linux-aarch64",
                path: "starpls",
            },
        },
    },
    "unused-deps": buildtools("unused-deps"),
};
